In [4]:
import sys
sys.path.append("../")
import chess
import numpy as np
from chess_engine.src.model.classes.bitboard_processing.bitboard_creator import Bitboard_Creator, bitboards_to_array, sample_bitboard_dict


In [5]:
bc = Bitboard_Creator()
board = chess.Board()

In [7]:
int_boards = bc.get_all_bitboards(board)
int_boards.values()

dict_values(['65280', '66', '36', '129', '8', '16', '71776119061217280', '4755801206503243776', '2594073385365405696', '9295429630892703744', '576460752303423488', '1152921504606846976'])

In [12]:
np.array(list(int_boards.values()), dtype=np.uint64)

array([              65280,                  66,                  36,
                       129,                   8,                  16,
         71776119061217280, 4755801206503243776, 2594073385365405696,
       9295429630892703744,  576460752303423488, 1152921504606846976],
      dtype=uint64)

In [13]:
def get_basic():
    bb = np.array(list(int_boards.values()), dtype=np.uint64)
    result = np.array([1.0,0.0,0.0])
    return bb, result

In [14]:
get_basic()

(array([              65280,                  66,                  36,
                        129,                   8,                  16,
          71776119061217280, 4755801206503243776, 2594073385365405696,
        9295429630892703744,  576460752303423488, 1152921504606846976],
       dtype=uint64),
 array([1., 0., 0.]))

In [15]:
bb1, res1 = get_basic()
bb2, res2 = get_basic()

In [16]:
bb1.shape

(12,)

In [17]:
p_bb1 = bitboards_to_array(bb1)
p_bb2 = bitboards_to_array(bb2)

In [19]:
p_bb1.shape

(12, 8, 8)

In [26]:
np.stack([bb1,bb2]).shape

(2, 12)

(12, 8, 8)